db:
  image: postgres
temperature_monitor:
  build: ./
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - ./:/temperature_monitor
  ports:
    - "3000:3000"
  links:
    - db
  volumes_from:
    - box
  environment:
    SECRET_KEY_BASE: 8f2a6e2ece947b6acb092a78548cad1b0eb9a063107e6652f2677f10030d1dff8bb65a89b5dc2277fc66b1647e45be6b03e751bca4830f488ba67e5d84b81248
box:
  image: busybox
  volumes:
    - /box
